global proc AEvectorRampLookupPPTemplate ( string $nodeName )
{

	editorTemplate -beginScrollLayout;
	
	
	editorTemplate -cl 0  -beginLayout "Spline Attributes";		
	
	editorTemplate -addControl "inputMin"  ;
	editorTemplate -addControl "inputMax"  ;
	editorTemplate -addControl "outputMin" ;
	editorTemplate -addControl "outputMax" ;

	AEaddRampControl ($nodeName+".ramp");	
	editorTemplate -endLayout;

	editorTemplate -addExtraControls;
	editorTemplate -endScrollLayout;
	
}
